micronaut:
  server:
    port: '${PORT}'
  application:
    name: phonebook
  caches:
    phonebook:
      charset: UTF-8
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /doc/**

fauna:
  secret: '${FAUNA_KEY}'
  endpoint: https://db.eu.fauna.com:443
  graphql:
    endpoint: https://graphql.eu.fauna.com/graphql
    enabled: false
