micronaut:
  application:
    name: phonebook
  caches:
    phonebook:
      charset: UTF-8
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /spec/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /doc/**

endpoints:
  caches:
    enabled: true
    # sensitive: false

fauna:
  secret: '${FAUNA_KEY}'
