micronaut:
  application:
    name: phonebook
  caches:
    phonebook:
      charset: UTF-8
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /doc/**

endpoints:
  caches:
    enabled: true
    # sensitive: false

fauna:
  secret: fnAEevmFvJAAx59IJcsQgFlMxWJ3_GVh2HPFECIF #'${FAUNA_KEY}'
  endpoint: https://db.eu.fauna.com:443
