name: Native image Heroku deployment

on:
  workflow_dispatch:
    branches:
      - master

jobs:
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "phone-book-fauna"
          heroku_email: "abondar1992@gmail.com"
          buildpack: https://github.com/jkutner/graal-buildpack
        env:
          HD_FAUNA_KEY: ${{secrets.FAUNA_KEY}}


