name: Native image Heroku deployment

on:
  workflow_dispatch:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: ayltai/setup-graalvm@v1
        with:
          java-version: 17
          graalvm-version: 21.3.0
      - name: Build
        uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
        with:
          arguments: nativeCompile
      - run: mkdir -p build/native/nativeCompile
      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: phonebook
          path: build/native/nativeCompile

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Download artifact
        uses: actions/download-artifact@master
        with:
          name: phonebook
          path: build/native/nativeCompile
      - name: Deploy
        run: heroku container:push -a phone-book-fauna web
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "phone-book-fauna"
          heroku_email: "abondar1992@gmail.com"
          buildpack: https://github.com/jkutner/graal-buildpack
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
          HD_FAUNA_KEY: ${{secrets.FAUNA_KEY}}


