name: Docker container  Heroku deployment

on:
  workflow_dispatch:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: ayltai/setup-graalvm@v1
        with:
          java-version: 17
          graalvm-version: 21.3.0
      - name: Build
        uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
        with:
          arguments: dockerfileNative
      - name: Deploy
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "phone-book-docker"
          email: "abondar1992@gmail.com"
          dockerfile_directory: build/docker/native-main
          dockerfile_name: DockerfileNative

        env:
          HD_FAUNA_KEY: ${{secrets.FAUNA_KEY}}
          HD_PORT: 8080

